[workspace]
members = ["common", "server"]

[workspace.dependencies]
uuid = { version = "1.2", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }

[profile.final]
inherits = "release"
strip = true
lto = true
codegen-units = 1
