[package]
name = "ecg-hub-server"
description = "Hub Server for ECG game"
authors = ["Timur Israpilov <very1fake.coder@gmail.com>"]
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
