[package]
name = "ecg-hub-server"
description = "Hub Server for ECG game"
authors = ["Timur Israpilov <very1fake.coder@gmail.com>"]
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { package = "ecg-hub-common", path = "../common" }

serde.workspace = true

axum = { version = "0.6", features = ["http2"] }
envy = "0.4"
hyper = { version = "0.14" }
serde_json = "1.0"
tokio = { version = "1.23", features = ["rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
